---
description: LOCALDB_ERROR_INTERNAL_ERROR
title: LOCALDB_ERROR_INTERNAL_ERROR |Microsoft Docs
ms.custom: ''
ms.date: 03/04/2017
ms.prod: sql
ms.reviewer: ''
ms.technology: performance
ms.topic: reference
ms.assetid: 60c7a47b-114c-441b-869e-9d8ebfe4148e
author: WilliamDAssafMSFT
ms.author: wiassaf
ms.openlocfilehash: 52653bc1610e27da8a8bcaf3e3420132d90eae4a
ms.sourcegitcommit: 0e0cd9347c029e0c7c9f3fe6d39985a6d3af967d
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/02/2020
ms.locfileid: "96506206"
---
# <a name="localdb_error_internal_error"></a>LOCALDB_ERROR_INTERNAL_ERROR
 [!INCLUDE [SQL Server](../../includes/applies-to-version/sqlserver.md)]
    
## <a name="details"></a>詳細  
  
| 属性 | 値 |
| --------- | ----- |
|製品名|SQL Server|  
|イベント ID|264|  
|イベント ソース|SQL Server Local Database Runtime 12.0|  
|コンポーネント|Local Database Runtime API|  
|メッセージ テキスト|ローカル データベース インスタンスの API メソッドの呼び出しで予期しないエラーが発生しました。 エラーの詳細については、Windows アプリケーション ログを参照してください。|  
  
## <a name="explanation"></a>説明  
 予期しないエラーが発生しました。  
  
## <a name="user-action"></a>ユーザーの操作  
 詳細をイベント ログで確認してください。  
  
  
