---
description: MSSQLSERVER_8680
title: MSSQLSERVER_8680 | Microsoft Docs
ms.custom: ''
ms.date: 04/04/2017
ms.prod: sql
ms.reviewer: ''
ms.technology: supportability
ms.topic: language-reference
helpviewer_keywords:
- 8680 (Database Engine error)
ms.assetid: 79f7270e-e4df-4f4e-bc78-2dcad6a9f140
author: MashaMSFT
ms.author: mathoma
ms.openlocfilehash: ea03c289fb8138854b06ce2e3ba3298052e8253e
ms.sourcegitcommit: e700497f962e4c2274df16d9e651059b42ff1a10
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 08/17/2020
ms.locfileid: "88420886"
---
# <a name="mssqlserver_8680"></a>MSSQLSERVER_8680
 [!INCLUDE [SQL Server](../../includes/applies-to-version/sqlserver.md)]
  
## <a name="details"></a>詳細  
  
| 属性 | 値 |  
| :-------- | :---- |  
|製品名|SQL Server|  
|イベント ID|8680|  
|イベント ソース|MSSQLSERVER|  
|コンポーネント|SQLEngine|  
|シンボル名|REMOTE_ERR|  
|メッセージ テキスト|内部クエリ プロセッサ エラー:リモート クエリ フェーズを処理中に、クエリ プロセッサで予期しないエラーが発生しました。|  
  
## <a name="explanation"></a>説明  
クエリ処理中に内部エラーが発生しました。  
  
## <a name="user-action"></a>ユーザーの操作  
マイクロソフト カスタマー サポート サービス (CSS) に連絡し、エラーの説明とトレースまたはダンプ (取得可能な場合) を報告してください。  
  
